from __future__ import print_function
import requests
import json
import argparse
from config import APP_ID, ACCESS_KEY

# AppSheet API configuration
API_BASE_URL = f'https://api.appsheet.com/api/v2/apps/{APP_ID}'

def get_headers():
    """Get the headers for AppSheet API requests."""
    return {
        'Authorization': f'Bearer {ACCESS_KEY}',
        'Content-Type': 'application/json',
        'ApplicationAccessKey': ACCESS_KEY
    }

def delete_table(table_name):
    """Delete a table from AppSheet."""
    url = f'{API_BASE_URL}/tables/{table_name}/Action'
    
    payload = {
        "Action": "DeleteTable",
        "Properties": {
            "Locale": "en-US",
            "Timezone": "UTC"
        },
        "TableName": table_name
    }

    try:
        response = requests.post(url, headers=get_headers(), json=payload)
        response.raise_for_status()
        print(f"Deleted table {table_name}")
        return True
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 404:
            print(f"Table {table_name} does not exist")
            return True
        raise

def create_table(table_name, columns):
    """Create a new table in AppSheet."""
    url = f'{API_BASE_URL}/tables/{table_name}/Action'
    
    payload = {
        "Action": "CreateTable",
        "Properties": {
            "Locale": "en-US",
            "Timezone": "UTC"
        },
        "TableName": table_name,
        "Columns": columns
    }

    try:
        response = requests.post(url, headers=get_headers(), json=payload)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.HTTPError as e:
        print(f"HTTP Error: {e}")
        print(f"Response content: {e.response.text}")
        raise
    except json.JSONDecodeError as e:
        print(f"JSON Decode Error: {e}")
        print(f"Response content: {response.text}")
        raise
    except Exception as e:
        print(f"Unexpected error: {e}")
        raise

def main():
    """Create all the necessary tables in AppSheet."""
    parser = argparse.ArgumentParser(description='Create or recreate AppSheet tables')
    parser.add_argument('--wipe', action='store_true', help='Delete existing tables before creating new ones')
    args = parser.parse_args()

    # Tables to create in order (respecting dependencies)
    tables = [
        "Show_Attendees",
        "Show_Bands",
        "ShowList",
        "Attendees",
        "VenueList",
        "Bands",
        "Band_Groups"
    ]

    try:
        if args.wipe:
            print("Wiping existing tables...")
            for table in tables:
                delete_table(table)
            print("All existing tables deleted")

        # Band_Groups table
        band_groups_columns = [
            {
                "Name": "_ID",
                "Type": "Integer",
                "IsPrimaryKey": True,
                "IsAutoIncrement": True
            },
            {
                "Name": "PrimaryBand",
                "Type": "Text",
                "IsUnique": True
            },
            {
                "Name": "_CreatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            },
            {
                "Name": "_UpdatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            }
        ]
        print("Creating Band_Groups table...")
        create_table("Band_Groups", band_groups_columns)

        # Bands table
        bands_columns = [
            {
                "Name": "_ID",
                "Type": "Integer",
                "IsPrimaryKey": True,
                "IsAutoIncrement": True
            },
            {
                "Name": "Name",
                "Type": "Text",
                "IsUnique": True
            },
            {
                "Name": "NormalizedName",
                "Type": "Text",
                "IsComputed": True
            },
            {
                "Name": "GroupID",
                "Type": "Integer",
                "IsNullable": True,
                "Reference": {
                    "Table": "Band_Groups",
                    "Column": "_ID"
                }
            },
            {
                "Name": "_CreatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            },
            {
                "Name": "_UpdatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            }
        ]
        print("Creating Bands table...")
        create_table("Bands", bands_columns)

        # VenueList table
        venue_list_columns = [
            {
                "Name": "_ID",
                "Type": "Integer",
                "IsPrimaryKey": True,
                "IsAutoIncrement": True
            },
            {
                "Name": "Name",
                "Type": "Text",
                "IsUnique": True
            },
            {
                "Name": "Location",
                "Type": "Text"
            },
            {
                "Name": "Closed",
                "Type": "Boolean"
            },
            {
                "Name": "_CreatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            },
            {
                "Name": "_UpdatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            }
        ]
        print("Creating VenueList table...")
        create_table("VenueList", venue_list_columns)

        # Attendees table
        attendees_columns = [
            {
                "Name": "_ID",
                "Type": "Integer",
                "IsPrimaryKey": True,
                "IsAutoIncrement": True
            },
            {
                "Name": "Name",
                "Type": "Text",
                "IsUnique": True
            },
            {
                "Name": "_CreatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            },
            {
                "Name": "_UpdatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            }
        ]
        print("Creating Attendees table...")
        create_table("Attendees", attendees_columns)

        # ShowList table
        show_list_columns = [
            {
                "Name": "_ID",
                "Type": "Integer",
                "IsPrimaryKey": True,
                "IsAutoIncrement": True
            },
            {
                "Name": "Date",
                "Type": "Date"
            },
            {
                "Name": "VenueID",
                "Type": "Integer",
                "Reference": {
                    "Table": "VenueList",
                    "Column": "_ID"
                }
            },
            {
                "Name": "Confirmed",
                "Type": "Boolean"
            },
            {
                "Name": "Event",
                "Type": "Text"
            },
            {
                "Name": "Notes",
                "Type": "Text",
                "IsNullable": True
            },
            {
                "Name": "_CreatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            },
            {
                "Name": "_UpdatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            }
        ]
        print("Creating ShowList table...")
        create_table("ShowList", show_list_columns)

        # Show_Bands table
        show_bands_columns = [
            {
                "Name": "_ID",
                "Type": "Integer",
                "IsPrimaryKey": True,
                "IsAutoIncrement": True
            },
            {
                "Name": "ShowID",
                "Type": "Integer",
                "Reference": {
                    "Table": "ShowList",
                    "Column": "_ID"
                }
            },
            {
                "Name": "BandID",
                "Type": "Integer",
                "Reference": {
                    "Table": "Bands",
                    "Column": "_ID"
                }
            },
            {
                "Name": "_CreatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            }
        ]
        print("Creating Show_Bands table...")
        create_table("Show_Bands", show_bands_columns)

        # Show_Attendees table
        show_attendees_columns = [
            {
                "Name": "_ID",
                "Type": "Integer",
                "IsPrimaryKey": True,
                "IsAutoIncrement": True
            },
            {
                "Name": "ShowID",
                "Type": "Integer",
                "Reference": {
                    "Table": "ShowList",
                    "Column": "_ID"
                }
            },
            {
                "Name": "AttendeeID",
                "Type": "Integer",
                "Reference": {
                    "Table": "Attendees",
                    "Column": "_ID"
                }
            },
            {
                "Name": "_CreatedAt",
                "Type": "DateTime",
                "IsAutoGenerated": True
            }
        ]
        print("Creating Show_Attendees table...")
        create_table("Show_Attendees", show_attendees_columns)

        print("All tables created successfully!")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == '__main__':
    main() 